### ISSUE TITLE
Branch name

### ISSUE THREAD

**Issue by gibernas** [duckietown/challenge-aido_LF-baseline-duckietown#12]
@liampaull 
https://docs.duckietown.org/daffy/AIDO/out/ros_baseline.html refers to daffy branch, which is missing here. Are we simply coping over the `aido2` branch or are there changes coming?

**Comment by liampaull** [comment]
sorry forgot to push the branch - just did. There are changes to upgrade to `daffy` from the sim and few other small fixes.
