### ISSUE TITLE
ROSParam Error

### ISSUE THREAD

**Issue by bhairavmehta95** [duckietown/challenge-aido_LF-baseline-duckietown#2]
```
step step1-simulation : InvalidSubmission:
step step1-simulation : Traceback (most recent call last):
step step1-simulation :   File "/workspace/src/duckietown-challenges/src/duckietown_challenges/cie_concrete.py", line 486, in wrap_evaluator
step step1-simulation :     raise InvalidSubmission(out[SPECIAL_INVALID_SUBMISSION])
step step1-simulation : InvalidSubmission: Invalid solution:
step step1-simulation : Traceback (most recent call last):
step step1-simulation :   File "/workspace/src/duckietown-challenges/src/duckietown_challenges/cie_concrete.py", line 585, in wrap_solution
step step1-simulation :     solution.run(cis)
step step1-simulation :   File "./solution.py", line 89, in run
step step1-simulation :     raise InvalidSubmission(str(e))
step step1-simulation : InvalidSubmission: error loading <rosparam> tag:
step step1-simulation : 	'param' attribute must be set for non-dictionary values
step step1-simulation : XML is <rosparam command="load" file="$(find duckietown)/config/$(arg config)/line_detector/$(arg node_name)/$(arg param_file_name).yaml"/>
step step1-simulation : 
step step1-simulation : 
```

I am trying to run this repository, which last I checked (~10 days ago) seemed okay (i.e submissions went through, and worked fine).

When I manually start and enter the container (`docker run...`) and run the same commands, everything seems to start fine, but when I use `dts challenges [evaluate|submit]`, I always get this error r.e the parameter / config file.

These are the same commands copied from the `master.launch` file in the Software repo (in this repository, its called `lf_slim.launch`), and since I don't any errors when I manually run `roslaunch` or use the roslaunch python API, I have to assume that there is something else that changes it inside of the evaluator. I believe it has to do with how the evaluator runs the solution.py file, but I don't know.

**Comment by liampaull** [comment]
how can I reproduce ?

**Comment by liampaull** [comment]
@bhairavmehta95 I think this could be the problem: https://github.com/duckietown/challenge-aido1_LF1-template-ros/blob/aido1_remote3-v3/Dockerfile#L39

that is the wrong path - we need to take the devel out. I will try it and test

**Comment by bhairavmehta95** [comment]
Hmm okay. I fixed this, but I still don't think its the issue.

It seems to be some issue only when the parameter files are loaded - When I comment out everything except the inverse kinematic node and the ground projection node (the 2 out of the 5 that **do not load parameter files** in the node), it works completely fine.

**Comment by liampaull** [comment]
no I'm pretty sure this fixes it. the root is that since you haven't sourced the ros stuff the "find" command doesn't work. I'm onto a new error now
