### ISSUE TITLE
challenge_results.yaml does not exit 

### ISSUE THREAD

**Issue by liampaull** [duckietown/challenge-aido_LF-baseline-duckietown#3]
```
Uncaught exception while running Docker Compose:
Traceback (most recent call last):
  File "/project/src/duckietown_challenges_runner/runner.py", line 526, in run_one
    cr = read_challenge_results(wd)
  File "/project/src/duckietown-challenges/src/duckietown_challenges/challenge_results.py", line 63, in read_challenge_results
    raise Exception(msg)
Exception: File u'/tmp/duckietown/DT18/evaluator/executions/aido1_LF1_r3-v3/submission406/step1-simulation-rudolf-8-job3949/challenge-results/challenge_results.yaml' does not exist.
```

https://challenges.duckietown.org/v3/humans/submissions/406

**Comment by bhairavmehta95** [comment]
Ah, finally I'm on the same error. Thank you for your help debugging! I'll figure this out and close this asap.

**Comment by hristo-vrigazov** [comment]
@bhairavmehta95  I am getting the same error when trying to evaluate, here's the full stack trace:

```
19:49:03 solution Traceback (most recent call last):
19:49:03 solution   File "./solution.py", line 12, in <module>
19:49:03 solution     from rosagent import ROSAgent
19:49:03 solution   File "/workspace/rosagent.py", line 3, in <module>
19:49:03 solution     from duckietown_msgs.msg import Twist2DStamped, WheelsCmdStamped
19:49:03 solution ImportError: No module named duckietown_msgs.msg
INFO:evaluator:container solution terminated with 1
ERROR:evaluator:solution exited with code 1
ERROR:evaluator:Uncaught exception while running Docker Compose:
Traceback (most recent call last):
  File "/project/src/duckietown_challenges_runner/runner.py", line 526, in run_one
    cr = read_challenge_results(wd)
  File "/project/src/duckietown-challenges/src/duckietown_challenges/challenge_results.py", line 63, in read_challenge_results
    raise Exception(msg)
Exception: File u'output/step1-simulation.tmp/challenge-results/challenge_results.yaml' does not exist.

```

It looks like some ROS message types are missing.

**Comment by bhairavmehta95** [comment]
Hi @hristo-vrigazov , thanks for testing. Yes - you are correct. This has to do with the way / order that the various environment / bash files are sourced. We should have a solution within the hour.

**Comment by liampaull** [comment]
I think I got it - the source commands in upstream dockerfile are out of order. See commit: https://github.com/duckietown/challenge-aido1_LF1-template-ros/commit/e89d9bcffac4de681d6126c5e26ceb472ef34bee

@bhairavmehta95 I'm back to getting the old error - it must have to do with the docker builds, I'm not sure I'm doing it right - can you make sure that the building is happening properly ?

**Comment by AndreaCensi** [comment]
One piece of advice: always run "evaluate" locally - it usually is easier than debugging remote executions.
