### ISSUE TITLE
Wheels Node Driver

### ISSUE THREAD

**Issue by bhairavmehta95** [duckietown/challenge-aido_LF-baseline-duckietown#8]
We need to fix and push a change for [this issue](https://github.com/duckietown/Software/issues/419) and then can change the Dockerfile to repull from the aido2 template.

**Comment by liampaull** [comment]
see PR #420 in Software - does that look like it should fix the problem?

**Comment by bhairavmehta95** [comment]
Potentially - I don't have enough time to test this atm, so I will keep this open until those changes are merged.
