### ISSUE TITLE
Low framerate of images from the simulator.

### ISSUE THREAD

**Issue by RamiNaim** [duckietown/challenge-aido_LF-baseline-duckietown#9]
Good Day!
While working in the submission I've recorded several rosbag files for debugging during the process of local evaluation of the baseline solution. I found out that topic with the raw image from the simulator publishes messages with a frequency of approximately 2 HZ. If I understand correctly, such low framerate can severely affect the baseline lane following solution. So my question is: is there any way of increasing the framerate with which simulator publishes raw image? I have tried increasing the value of `rospy.rate()`, but it did not result in anything.
Thank you in advance!

**Comment by AndreaCensi** [comment]
The simulator is not meant to operate in realtime.

The glue node should use the data timestamp instead of the wall time. 

@bhairavmehta95 @liampaull

**Comment by RamiNaim** [comment]
I would like to clarify that I understood you correctly. Is it ensured that simulator publishes observation from each step and do not skip any frames in between two steps? And these correct observations are published with the rate at 2 HZ?

**Comment by bhairavmehta95** [comment]
So this is not necessarily an issue with the simulator, but what's being recorded is the output of the lane following stack, which operates at a much slower speed than the actual simulator. 

If you use the lanefollowing stack we provide, this is the type of performance you'll see - this is not to say that no optimizations are possible (**hint**, there are!) but out of the box, this is expected performance.
